name: Process submission

on:
  push:
    branches:
      - main

jobs:
  process_submission:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # if needed

      - name: Run the Python script
        run: python process_submission.py

      - name: Upload summary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: summary
          path: summary.md

      - name: Commit summary to the repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add summary.md
          git commit -m "Update summary report"
          git push
